# Generated by Django 4.2.5 on 2023-09-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lip_app', '0002_remove_category_book_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
